# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-12 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
