# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-12 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_questionanswertest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionAnswerTest',
        ),
    ]
