# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-21 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ldap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetOTC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, verbose_name='code')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('applied_on', models.DateTimeField(blank=True, null=True, verbose_name='applied on')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_otcs', to='ldap.LdapUser', verbose_name='user')),
            ],
            options={
                'ordering': ['user', '-id'],
                'verbose_name': 'password reset OTC',
                'verbose_name_plural': 'password reset OTCs',
            },
        ),
    ]
