# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-30 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0014_auto_20180111_1113'),
        ('otc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartShareOTC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, verbose_name='code')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('applied_on', models.DateTimeField(blank=True, null=True, verbose_name='applied on')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_share_otcs', to='charts.Chart', verbose_name='chart')),
            ],
            options={
                'verbose_name_plural': 'char share OTCs',
                'verbose_name': 'char share OTC',
            },
        ),
    ]
