# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-04 12:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('otc', '0002_chartshareotc'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartshareotc',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otc_chartshareotc_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='chartshareotc',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otc_chartshareotc_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='chartshareotc',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='updated on'),
        ),
    ]
