# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-02 12:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0026_auto_20180903_0908'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('otc', '0003_auto_20180904_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodShareOTC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated on')),
                ('code', models.UUIDField(default=uuid.uuid4, verbose_name='code')),
                ('applied_on', models.DateTimeField(blank=True, null=True, verbose_name='applied on')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otc_periodshareotc_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_share_otcs', to='metrics.Period', verbose_name='period')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otc_periodshareotc_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otcs_shared_period', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Period share OTC',
                'verbose_name_plural': 'Period share OTCs',
            },
        ),
    ]
